# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STFilterDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for STFilterDemo
  
  pod 'GPUImage', '~> 0.1.7'
  
  target 'STFilterDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
